Sidebar Component
CPSECapstone/Overcast pull request #23
Opened 2021-03-08 09:31 UTC by ShreyaTumma

**Overview**
Create a collapsible and expandable sidebar menu component that integrates with all frames. The applications listed in the sidebar menu are added to the menuListItemsConfig list and these applications route to their respective pages when clicked on. 
The page the user is on matches which application is highlighted in the menu's list.

As discussed in the slack channel, I did not style the highlighted application exactly to match the Figma design, as the inverse curve proved difficult to implement. Another task should be opened to address the advanced styling.

**Screenshots**
![PRSidebar](https://user-images.githubusercontent.com/35640017/110302263-e865fd80-7fad-11eb-8dfb-ed008b62055e.JPG)
![PRSidebarExpanded](https://user-images.githubusercontent.com/35640017/110302288-eef47500-7fad-11eb-9e9c-6fffc2918342.JPG)

Closes [OV-58](http://platinum.cscaws.com:8080/browse/OV-58)

2021-03-09 01:56 UTC, glkidd requested changes
Left a couple comments and besides that, the only thing I'd like is if we could maybe center the question mark icon a little better?

2021-03-09 01:56 UTC, glkidd commented on cloud-haven-react-app/src/components/Sidebar/Sidebar.js
> +    <li key={listID} id={listID}>
Could we indent the whole list item component?

2021-03-09 01:56 UTC, glkidd commented on cloud-haven-react-app/src/components/Sidebar/Sidebar.js
> +export default Sidebar;
Add a newline at the end of the file

2021-03-09 21:46 UTC, patrickbartlett reviewed
looks good, just needs centering on the question mark icon

2021-03-09 22:13 UTC, turrence approved these changes

2021-03-10 07:04 UTC, glkidd approved these changes
Looks great! Really good work :)

2021-03-10 09:59 UTC, patrickbartlett approved these changes

2021-03-10 19:59 UTC, turrence approved these changes

2021-03-11 01:37 UTC, merged