Front end signup form
CPSECapstone/Overcast pull request #5
Opened 2020-10-27 23:05 UTC by ShreyaTumma

Sign up form component is structured based on the mid fidelity prototype and the submit button creates a JSON object.

Paired programming task with Terence.

2020-10-29 02:15 UTC, Michelle5102 reviewed
Just a couple minor things, but looks good!

2020-10-29 02:15 UTC, Michelle5102 commented on cloud-haven-react-app/src/components/SignUp/SignUp.js
> +                    name="password1"
```suggestion
                    name="password"
```
I think this might be a typo. Is there a reason it was called "password1?"

2020-10-29 02:15 UTC, Michelle5102 commented on cloud-haven-react-app/src/components/components.js
> +export {default as SignUp} from './SignUp/SignUp';
```suggestion
export {default as SignUp} from './SignUp/SignUp';

```
GitHub I think requires a newline at the end of files. Looks like I had originally left a newline off (oops, my bad), but maybe we could add one in with this PR?

2020-10-29 02:15 UTC, Michelle5102 commented on cloud-haven-react-app/src/components/SignUp/SignUp.css
> +}
```suggestion
}

```
GitHub prefers newlines at the end of files for their "diff" logic. At least, I think that's why they ask for it.

2020-10-29 02:18 UTC, Michelle5102 approved these changes
CR 👍

2020-10-29 02:27 UTC, glkidd approved these changes
We will definitely need to change up the UI a bit but looks good!

2020-10-29 02:41 UTC, glkidd requested changes
I think we need to change the front-end to match the Figma more and we should be using bootstrap components like we discussed.

2020-10-29 04:11 UTC, ShreyaTumma commented
That sounds good!
Can we merge this branch with main? Michelle and I worked on API function calls for the sign up component and that branch is dependent on this one.
We can make modifying the SignUp component as a new task in Jira.

2020-10-29 04:20 UTC, glkidd commented
> That sounds good!
> Can we merge this branch with main? Michelle and I worked on API function calls for the sign up component and that branch is dependent on this one.
> We can make modifying the SignUp component as a new task in Jira.

No let's not merge this yet, just pull from the branch on your branch for the API functions. Run 'git pull origin front-end-signup-form'

2020-10-29 04:43 UTC, Michelle5102 requested changes
>  We will just move this task over to our next sprint.
Thinking about it, I agree. Let's merge anything that we're not completely done with whenever possible. We can finish it up at the beginning of next sprint.

2020-11-11 02:29 UTC, patrickbartlett approved these changes
beautiful

2020-11-11 02:36 UTC, Michelle5102 reviewed
This should submit the username and password to the api. In the interest of expediency, I'm okay with if you guys want to make another issue for handling this (and put it on the current sprint)

2020-11-11 02:36 UTC, Michelle5102 commented on cloud-haven-react-app/src/components/SignUp/SignUp.js
> +        alert(JSON.stringify(signUpData))
This function should call the api function for signing up

2020-11-11 02:39 UTC, Michelle5102 commented on cloud-haven-react-app/src/components/SignUp/SignUp.js
> +        alert(JSON.stringify(signUpData))
This is covered in the database PR, so I suppose it's okay

2020-11-11 02:40 UTC, Michelle5102 approved these changes

2020-11-11 02:41 UTC, merged